### PR TITLE
Fix python3 setup.py error with LC_ALL=C

### PR DESCRIPTION
**Pull request by likema**
```shell
File setup.py, line 15, in <module>
    long_description=open('README.md', 'r').read(),
File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1315: ordinal not in range(128)
```

### CODE REVIEW

**Comment by Rafiot** [comment]
I'm pretty sure that if you have this locale, you will have other issues with the module. What about fixing the locale systemwide instead?

**Comment by likema** [comment]
No. I used this branch to solve it.

LC_ALL=C is default locale in Docker container.

**Comment by Rafiot** [comment]
Isn't that procedure better? => https://stackoverflow.com/questions/28405902/how-to-set-the-locale-inside-a-ubuntu-docker-container#28406007

**Comment by likema** [comment]
No. 

In Python 3, there is no `unicode` type, while `str` always represent Unicode.
 
The original code assumes locale is UTF-8. If locale is C and `REAMD.md` is UTF-8, 

```python
open('README.md', 'r').read()
```
`open` with `r` will conside `README.md` as ASCII and try to convert it to Unicode because `read` return `str` type so that exception is raised.

In contrast, `open` with `rb` will consider `README.md` as bytes without conversion. `decode` it to UTF-8 since we know that `README.md` is UTF-8 encoding.

**Comment by Rafiot** [comment]
Yes, I get that, but why not fixing the locale in docker instead of changing this library?

**Comment by likema** [comment]
I found it can not be fixed by

```shell
export LC_ALL=UTF-8 
export LANG=UTF-8
export LANGUAGE=UTF-8
```
It would encounter the same error.

The docker image, e.g. ubuntu:16.04, lacks a few language related packages unless installing it in Dockerfile, but that would increase the image size.

**Comment by Rafiot** [comment]
And what happen of you do that: https://webkul.com/blog/setup-locale-python3/

It shouldn't increase the image size.

**Comment by likema** [comment]
Run a Ubuntu 18.04 container by

```shell
docker run -ti --rm ubuntu:bionic
```

and 

```shell
locale-gen en_US.UTF-8
```

reports:

```
bash: locale-gen: command not found
```

**Comment by likema** [comment]
I know how to solve it by installing `locales`. But I want to keep my program running correctly without it.

**Comment by Rafiot** [comment]
I tested, and this one work: 

```bash 
docker run -e LANG=C.UTF-8 -e LC_ALL=C.UTF-8 -it --rm ubuntu:bionic
# install python3, python3-pip and git - then git clone, cd in the directory, pip3 install .
```

**Comment by likema** [comment]
It works.

**Comment by Rafiot** [comment]
Excellent, thank you for the feedback!

**Pull request closed without merging**
